### ISSUE TITLE
authentication issue on warewulf-node-image Rocky9.2

### ISSUE THREAD

**Issue by kelbstf** [hpcng/warewulf-node-images#30]
Hello,

i hope it is o.k. to post here as non-contributor?
If not, please remove my post, and sorry then.
If so: i used HPCNG prebuild Rocky 8 container images successfully under WW4.3 (OHPC) without any issues.

But after moving to WW4.4 and importing "docker://ghcr.io/hpcng/warewulf-rockylinux:9.2" i can't manage to login to the provisioned node, neither via SSH nor locally directly to the physical provisioned node. 

The authentication always fails for root and custom users added later with error messages like:

"root: audit: type=1400: avc: denied { transition } for pid=1479 comm="login" path="/usr/bin/bash" dev="rootfs" ino=610 secontext=system_u:system_r:kernel_t:s0 tcontext=unconfined_u:unconfined_r:s0 tclass=process permissive=0
no shell: Permission denied"

Changing the tcontext to system_u on /usr recursively (including bash therefore) in the CHROOT did not help the problem...

But configuring selinux to permissive "resolves" the problem.

Would there possibly be an option to have the option to obtain a container with the canonical selinux labels? That ould be great from my point of view.
Or is there a specific reason for the uncommon labels, that i am not aware of?
So far i provisioned compute nodes always with selinux enabled, in particular those for interactive logins...

Best regards

**Comment by anderbubble** [comment]
@kelbstf absolutely it's ok for you to raise an issue here.

I suspect that the issue you're having is with SELinux. Right now, as a result of how these images were developed in the first place, the Rocky Linux 8.x images have SELinux disabled (I think not even installed) but the 9.x images have SELinux enabled. Unfortunately, SELinux doesn't work in the default Warewulf node configuration.

You can either disable selinux in the image (update `/etc/selinux/config` to set `SELINUX=disabled`) or update your profile or node config to use `tmpfs` rather than `rootfs`. (The default `rootfs` doesn't support SELinux types.)

```
wwctl profile set default \
  --root=tmpfs \
  --kernelargs="quiet crashkernel=no vga=791 net.naming-scheme=v238 rootfstype=ramfs"
```

**Comment by kelbstf** [comment]
Hello @anderbubble

thank you very much for your very helpful and fast answer.
I didn't know about the missing xattr support of rootfs, mislead by the "seclabel" mount option i found.

I tested switching to tmpfs as you proposed and it works well.
Just had to relabel sysfs, but that's possibly a leftover from my own previous debugging.

Now i am a bit torn: is there any penalty for switching from rootfs to ramfs/tmpfs?
If it would just be a presumed (slightly?) higher memory overhead (bec. additional features), i would go for it, at least for the interactive nodes.
But i don't have a very strong requirement of selinux on compute nodes, other than i have the habit to keep it ON always on any systems by default, and therefore also used it on compute nodes, because i did not experience unsurmountable issues so far...

For non interactive nodes i would trade in selinux for any tangible hpc related edge of rootfs over tmpfs, if there was one.


Best

**Comment by anderbubble** [comment]
I haven't done a comparison of ramfs vs tmpfs. I've been planning to advocate for a switch to tmpfs by default in the future.

But, if you prefer, disabling selinux in the image is relatively trivial as well. I'd like to adjust these images to at least make them consistent in the future. Just haven't gotten to it yet.
