### ISSUE TITLE
Support RHEL8 as container image

### ISSUE THREAD

**Issue by josedev-union** [hpcng/warewulf-node-images#8]
Hi folks.
I have been using RHEL8 for servers because our system has a license with RHEL8.
I can find rocky8 image from https://hub.docker.com/u/warewulf but not rhel8.
Do you have any turnkey rhel8 image or at least any plan for building in the near future?
Or could you share how to build a bootable image so we can try it ourselves?
Thanks.

**Comment by anderbubble** [comment]
@josedev-union we don't currently have a RHEL8 image. I'd think you should be able to build one using https://github.com/hpcng/warewulf-node-images/tree/main/rockylinux-8 as an example but basing it on an upstream RHEL8 container image; but I suspect it wouldn't be within the terms of their license for us to distribute such an image.
